name: Markdown Checks

on:
  pull_request:

jobs:
  markdown-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Run Markdown lint
        uses: DavidAnson/markdownlint-cli2-action@v23
        with:
          globs: |
            ci_cd_reflection.md
            README.md

      - name: Run spell check
        uses: streetsidesoftware/cspell-action@v8
        with:
          files: |
            ci_cd_reflection.md
            README.md